<?php
declare(strict_types=1);

namespace Sangia\Gateway;

/**
 * HMAC-signed API key middleware.
 *
 * Key format (generated by Wizdam Sikola):
 *   wz_{user_id}_{issued_ts}_{hmac16}
 *
 * Shared secret: WIZDAM_SHARED_SECRET in both systems' .env
 * Revocation   : append key to writable/revoked_keys.txt (one per line)
 */
class ApiKeyMiddleware
{
    private const PREFIX       = 'wz_';
    private const KEY_TTL      = 31536000; // 1 year in seconds
    private const REVOKE_FILE  = __DIR__ . '/../writable/revoked_keys.txt';

    public static function validate(): void
    {
        $key = self::extractKey();

        if ($key === null) {
            self::reject('API key missing. Include X-API-Key header or ?api_key= parameter.');
        }

        if (!self::isValid($key)) {
            self::reject('Invalid or expired API key.');
        }

        if (self::isRevoked($key)) {
            self::reject('API key has been revoked.');
        }
    }

    /** Returns the caller's user_id from the key, or null if invalid. */
    public static function getUserId(): ?string
    {
        $key = self::extractKey();
        if ($key === null || !self::isValid($key)) return null;
        $parts = explode('_', $key, 4);
        return $parts[1] ?? null;
    }

    // ── Private helpers ──────────────────────────────────────────────────────

    private static function extractKey(): ?string
    {
        // Header takes precedence over query param
        $key = $_SERVER['HTTP_X_API_KEY']
            ?? $_SERVER['HTTP_AUTHORIZATION']  // "Bearer wz_..."
            ?? $_GET['api_key']
            ?? null;

        if ($key === null) return null;

        // Strip "Bearer " prefix if present
        if (str_starts_with($key, 'Bearer ')) {
            $key = substr($key, 7);
        }

        return str_starts_with($key, self::PREFIX) ? $key : null;
    }

    private static function isValid(string $key): bool
    {
        // wz_{user_id}_{issued_ts}_{hmac16}
        $parts = explode('_', $key, 4);
        if (count($parts) !== 4 || $parts[0] !== 'wz') return false;

        [, $userId, $issuedTs, $hmacPart] = $parts;

        if (!ctype_digit($issuedTs)) return false;
        if (time() - (int) $issuedTs > self::KEY_TTL) return false;

        $secret   = self::secret();
        $expected = substr(
            hash_hmac('sha256', $userId . ':' . $issuedTs, $secret),
            0, 16
        );

        return hash_equals($expected, $hmacPart);
    }

    private static function isRevoked(string $key): bool
    {
        if (!file_exists(self::REVOKE_FILE)) return false;
        $list = file(self::REVOKE_FILE, FILE_IGNORE_NEW_LINES | FILE_SKIP_EMPTY_LINES);
        return in_array($key, $list, true);
    }

    private static function secret(): string
    {
        return $_ENV['WIZDAM_SHARED_SECRET']
            ?? getenv('WIZDAM_SHARED_SECRET')
            ?: 'default-insecure-change-this-in-env';
    }

    private static function reject(string $message): never
    {
        http_response_code(401);
        header('Content-Type: application/json; charset=utf-8');
        echo json_encode([
            'status'  => 'error',
            'code'    => 401,
            'message' => $message,
            'info'    => 'Dapatkan API key di Wizdam Sikola → Profil → API Keys',
        ]);
        exit;
    }

    // ── Key generation helper (digunakan oleh Wizdam Sikola) ─────────────────

    /**
     * Generates a signed API key for a given user_id.
     * Call this from Wizdam Sikola using the shared secret.
     *
     * @param string $userId   User identifier (e.g. "42" or "user@email.com")
     * @param string $secret   The WIZDAM_SHARED_SECRET
     * @return string          API key string to give to the user
     */
    public static function generateKey(string $userId, string $secret): string
    {
        $ts   = (string) time();
        $hmac = substr(hash_hmac('sha256', $userId . ':' . $ts, $secret), 0, 16);
        return self::PREFIX . $userId . '_' . $ts . '_' . $hmac;
    }
}
