<?php
declare(strict_types=1);

/**
 * Sangia API Engine — Entry Point
 *
 * All endpoints require a valid API key (X-API-Key header).
 * Keys are generated by Wizdam Sikola.
 */

require_once dirname(__DIR__) . '/library/autoload.php';

use Sangia\Api\Config\Config;
use Sangia\Api\Middleware\CorsMiddleware;
use Sangia\Api\Response;
use Sangia\Gateway\ApiKeyMiddleware;

// ── Boot ──────────────────────────────────────────────────────────────────────
Config::load();
CorsMiddleware::handle();

set_exception_handler(function (Throwable $e) {
    $debug = Config::get('APP_DEBUG', 'false') === 'true';
    Response::serverError($debug ? $e->getMessage() : 'Internal server error');
});

// ── Parse request ─────────────────────────────────────────────────────────────
$method = $_SERVER['REQUEST_METHOD'];
$uri    = rtrim(parse_url($_SERVER['REQUEST_URI'], PHP_URL_PATH) ?? '/', '/') ?: '/';

// ── Health / public endpoints (no key required) ───────────────────────────────
if ($uri === '/health' || $uri === '/api/v1/health') {
    Response::json(['status' => 'up', 'service' => 'Sangia API Engine', 'time' => date('c')]);
}

if ($uri === '/api/v1/sdg/versions' && $method === 'GET') {
    use Sangia\Core\Modules\SDG\Config\VersionConfig;
    $versions = [];
    foreach (VersionConfig::versions() as $v) {
        $cfg = VersionConfig::get($v);
        $versions[$v] = ['label' => $cfg['label'], 'weights' => array_diff_key($cfg, ['label'=>1,'thresholds'=>1])];
    }
    Response::json(['status' => 'success', 'data' => $versions]);
}

// ── API Key validation (all routes below require a key) ───────────────────────
ApiKeyMiddleware::validate();

// ── Helper: read JSON body ────────────────────────────────────────────────────
function jsonBody(): array {
    static $body;
    if ($body === null) {
        $raw  = file_get_contents('php://input');
        $body = is_string($raw) ? (json_decode($raw, true) ?? []) : [];
    }
    return $body;
}

// ── Route: SDG Classification — 6 versioned endpoints ────────────────────────
if (preg_match('#^/api/v1/sdg/(v0|v1|v2|v3|v4|v5|v5e)/classify$#', $uri, $m) && $method === 'POST') {
    $version = $m[1];
    $body    = jsonBody();
    $orcid   = trim($body['orcid']   ?? $_GET['orcid']   ?? '');
    $doi     = trim($body['doi']     ?? $_GET['doi']      ?? '');
    $title   = trim($body['title']   ?? '');
    $abstract = trim($body['abstract'] ?? '');
    $refresh = filter_var($body['refresh'] ?? $_GET['refresh'] ?? false, FILTER_VALIDATE_BOOLEAN);

    use Sangia\Core\Modules\SDG\Config\VersionConfig;
    use Sangia\Core\Modules\SDG\Controllers\SdgApi;
    use Sangia\Core\Modules\SDG\Services\SdgAnalyzer;
    use Sangia\Core\Modules\SDG\Services\SdgClassifier;
    use Sangia\Core\Modules\SDG\Services\Evaluator\LevelV4Evaluator;
    use Sangia\Core\Modules\SDG\Config\SdgDictionary;

    $versionCfg  = VersionConfig::get($version);
    $dictionary  = new SdgDictionary();
    $classifier  = new SdgClassifier($dictionary);
    $evaluator   = new LevelV4Evaluator();
    $analyzer    = new SdgAnalyzer($classifier, $evaluator, $dictionary, $versionCfg);
    $api         = new SdgApi($analyzer);

    if ($orcid) {
        Response::json($api->handleOrcidRequest($orcid, $refresh));
    } elseif ($doi) {
        Response::json($api->handleDoiRequest($doi, $refresh));
    } elseif ($title || $abstract) {
        // Direct text classification (no external API call)
        $result = $analyzer->analyzeWork($title, $abstract);
        Response::json(['status' => 'success', 'version' => $version, 'sdg_analysis' => $result]);
    } else {
        Response::json(['status' => 'error', 'message' => 'Provide orcid, doi, or title+abstract'], 400);
    }
}

// Alias: latest version at /api/v1/sdg/classify → v5
if ($uri === '/api/v1/sdg/classify' && $method === 'POST') {
    header('Location: /api/v1/sdg/v5/classify', true, 307);
    exit;
}

// ── Route: Scopus Author ──────────────────────────────────────────────────────
if ($uri === '/api/v1/scopus/author' && $method === 'GET') {
    use Sangia\Core\Modules\Scopus\ScopusModule;
    $authorId = trim($_GET['authorid'] ?? '');
    $count    = (int) ($_GET['count']   ?? 10);
    $refresh  = filter_var($_GET['refresh'] ?? false, FILTER_VALIDATE_BOOLEAN);

    if (empty($authorId)) Response::json(['status'=>'error','message'=>'authorid required'], 400);

    Response::json((new ScopusModule())->getAuthor($authorId, $count, $refresh));
}

// ── Route: ORCID Profile ──────────────────────────────────────────────────────
if ($uri === '/api/v1/orcid/profile' && $method === 'GET') {
    use Sangia\Core\Modules\ORCID\OrcidModule;
    $orcid   = trim($_GET['orcid']   ?? '');
    $refresh = filter_var($_GET['refresh'] ?? false, FILTER_VALIDATE_BOOLEAN);
    $limit   = (int) ($_GET['limit'] ?? 50);

    if (empty($orcid)) Response::json(['status'=>'error','message'=>'orcid required'], 400);

    Response::json((new OrcidModule())->getProfile($orcid, $refresh, $limit));
}

// ── Route: Citation (DOI) ─────────────────────────────────────────────────────
if ($uri === '/api/v1/citation/doi' && $method === 'GET') {
    use Sangia\Core\Modules\Citation\CitationModule;
    $doi     = trim($_GET['doi']     ?? '');
    $limit   = (int) ($_GET['limit'] ?? 15);
    $refresh = filter_var($_GET['refresh'] ?? false, FILTER_VALIDATE_BOOLEAN);

    if (empty($doi)) Response::json(['status'=>'error','message'=>'doi required'], 400);

    Response::json((new CitationModule())->getCitations($doi, $limit, $refresh));
}

// ── Route: Journal Metrics (Scopus) ──────────────────────────────────────────
if ($uri === '/api/v1/journal/metrics' && $method === 'GET') {
    use Sangia\Core\Modules\Journal\JournalModule;
    $issn    = trim($_GET['issn']    ?? '');
    $refresh = filter_var($_GET['refresh'] ?? false, FILTER_VALIDATE_BOOLEAN);

    if (empty($issn)) Response::json(['status'=>'error','message'=>'issn required'], 400);

    Response::json((new JournalModule())->getMetrics($issn, $refresh));
}

// ── Route: SINTA Journal Score ────────────────────────────────────────────────
if ($uri === '/api/v1/sinta/score' && $method === 'GET') {
    use Sangia\Core\Modules\Sinta\SintaModule;
    $issn    = trim($_GET['issn']    ?? '');
    $refresh = filter_var($_GET['refresh'] ?? false, FILTER_VALIDATE_BOOLEAN);

    if (empty($issn)) Response::json(['status'=>'error','message'=>'issn required'], 400);

    Response::json((new SintaModule())->getScore($issn, $refresh));
}

// ── Route: Wizdam Impact Score ────────────────────────────────────────────────
if ($uri === '/api/v1/impact/calculate' && $method === 'POST') {
    use Sangia\Core\Modules\WizdamScore\WizdamScoreEngine;
    $body      = jsonBody();
    $orcid     = trim($body['orcid']      ?? '');
    $scopusId  = trim($body['scopus_id']  ?? '') ?: null;
    $social    = $body['social']           ?? [];
    $economic  = $body['economic']         ?? [];
    $refresh   = filter_var($body['refresh'] ?? false, FILTER_VALIDATE_BOOLEAN);

    if (empty($orcid)) Response::json(['status'=>'error','message'=>'orcid required'], 400);

    Response::json((new WizdamScoreEngine())->calculate($orcid, $scopusId, $social, $economic, $refresh));
}

// ── Route: Admin — revoke a key ───────────────────────────────────────────────
if ($uri === '/api/v1/admin/keys/revoke' && $method === 'POST') {
    // Only service-level calls (Wizdam Sikola backend) should reach this
    $body = jsonBody();
    $key  = trim($body['key'] ?? '');
    if (empty($key)) Response::json(['status'=>'error','message'=>'key required'], 400);

    $revokeFile = dirname(__DIR__) . '/writable/revoked_keys.txt';
    @mkdir(dirname($revokeFile), 0755, true);
    file_put_contents($revokeFile, $key . PHP_EOL, FILE_APPEND | LOCK_EX);

    Response::json(['status' => 'success', 'message' => 'Key revoked']);
}

// ── Endpoint catalogue (no key required, for discovery) ───────────────────────
if ($uri === '/api/v1' || $uri === '/api') {
    Response::json([
        'service'   => 'Sangia API Engine',
        'version'   => 'v1',
        'endpoints' => [
            'GET  /health'                          => 'Service health check (no key)',
            'GET  /api/v1/sdg/versions'             => 'List SDG analysis versions (no key)',
            'POST /api/v1/sdg/v0/classify'          => 'SDG v0 — keyword-only (v1.1.7)',
            'POST /api/v1/sdg/v1/classify'          => 'SDG v1 — keyword + similarity',
            'POST /api/v1/sdg/v2/classify'          => 'SDG v2 — bilingual dict (v2.1.7)',
            'POST /api/v1/sdg/v3/classify'          => 'SDG v3 — contributor types (v3.1.7)',
            'POST /api/v1/sdg/v4/classify'          => 'SDG v4 — substantive+causal (v4.1.7)',
            'POST /api/v1/sdg/v5/classify'          => 'SDG v5 — causal-boosted stable (v5.1.8)',
            'POST /api/v1/sdg/v5e/classify'         => 'SDG v5e — metadata-enhanced (experimental)',
            'POST /api/v1/sdg/classify'             => 'SDG classify — alias for v5',
            'GET  /api/v1/scopus/author'            => 'Scopus author profile + publications',
            'GET  /api/v1/orcid/profile'            => 'ORCID researcher profile + works',
            'GET  /api/v1/citation/doi'             => 'Multi-source citation data for a DOI',
            'GET  /api/v1/journal/metrics'          => 'Scopus journal metrics (CiteScore, SJR, SNIP)',
            'GET  /api/v1/sinta/score'              => 'SINTA journal impact score',
            'POST /api/v1/impact/calculate'         => 'Wizdam Impact Score (composite)',
            'POST /api/v1/admin/keys/revoke'        => 'Revoke an API key (service calls only)',
        ],
        'auth'      => 'X-API-Key: wz_{user_id}_{timestamp}_{hmac16}',
        'key_info'  => 'Get your API key in Wizdam Sikola → Profile → API Keys',
    ]);
}

// ── 404 ───────────────────────────────────────────────────────────────────────
Response::json(['status' => 'error', 'message' => "Endpoint $method $uri not found"], 404);
