name: Build & Deploy Sangia-APIs

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    env:
      SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      SERVER: ${{ secrets.SERVER_HOST }}
      USER: ${{ secrets.SERVER_USERNAME }}
      TARGET: ${{ secrets.DEPLOY_PATH }}

    steps:
      - uses: actions/checkout@v4
      
      - name: Setup PHP & Composer
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          tools: composer:v2
          coverage: none
      
      - name: Build Production Dependencies
        run: composer install --no-dev --optimize-autoloader --no-interaction --prefer-dist
      
      - name: Purge Dev Files
        run: |
          rm -rf .github/ tests/
          rm -f .gitattributes .gitignore .gitkeep
          rm -f phpunit.xml phpunit.xml.dist
      
      - name: Deploy to cPanel via SSH
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ env.SSH_KEY }}
          # PERBAIKAN: Tambahkan -o StrictHostKeyChecking=no
          ARGS: "-rlgoDzvc --delete -o StrictHostKeyChecking=no --exclude='.env' --exclude='writable/logs/' --exclude='writable/cache/'"
          SOURCE: "./"
          REMOTE_HOST: ${{ env.SERVER }}
          REMOTE_USER: ${{ env.USER }}
          TARGET: ${{ env.TARGET }}